### ISSUE TITLE
error using"  roslaunch d435i_xarm_setup d435i_xarm_auto_calib.launch" to calibrate my d435i 

### ISSUE THREAD

**Issue by AtariaLee** [xArm-Developer/xarm_ros#146]
**我按照流程使用`roslaunch d435i_xarm_setup d435i_xarm_auto_calib.launch`来对我的机器人和D435I相机进行手眼标定的时候，出现了错误。**
```
Traceback (most recent call last):
  File "/home/lee/catkin_ws/src/easy_handeye/easy_handeye/scripts/calibrate.py", line 5, in <module>
    from easy_handeye.handeye_server import HandeyeServer
  File "/home/lee/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_server.py", line 13, in <module>
    from easy_handeye.handeye_calibration_backend_opencv import HandeyeCalibrationBackendOpenCV
  File "/home/lee/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_calibration_backend_opencv.py", line 4, in <module>
    import transforms3d as tfs
ImportError: No module named transforms3d
[ INFO] [1668063405.418488973]: Expected frequency for depth = 30.00000
[ INFO] [1668063405.436060835]: Expected frequency for color = 30.00000
[ INFO] [1668063405.447246861]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1668063405.458059726]: setupStreams...
[ INFO] [1668063405.486661028]: SELECTED BASE:Depth, 0
[ INFO] [1668063405.493360180]: RealSense Node Is Up!
[ INFO] [1668063405.506696740]: Listening to '/attached_collision_object' for attached collision objects
Planning scene monitors started.
[ INFO] [1668063405.525067988]: Initializing OMPL interface using ROS parameters
[ INFO] [1668063405.536784107]: Using planning interface 'OMPL'
[ INFO] [1668063405.539086553]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1668063405.539502952]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1668063405.539708841]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1668063405.540099645]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1668063405.540303967]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1668063405.540506188]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1668063405.540531679]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1668063405.540541653]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1668063405.540549172]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1668063405.540556771]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1668063405.540564052]: Using planning request adapter 'Fix Start State Path Constraints'
[ WARN] [1668063405.624844332]: 
[xarm_realsense_handeyecalibration_eye_on_hand/easy_handeye_calibration_server-12] process has died [pid 8002, exit code 1, cmd /home/lee/catkin_ws/src/easy_handeye/easy_handeye/scripts/calibrate.py __name:=easy_handeye_calibration_server __log:=/home/lee/.ros/log/d5dbf184-60c4-11ed-ae88-d83bbfe17db4/xarm_realsense_handeyecalibration_eye_on_hand-easy_handeye_calibration_server-12.log].
log file: /home/lee/.ros/log/d5dbf184-60c4-11ed-ae88-d83bbfe17db4/xarm_realsense_handeyecalibration_eye_on_hand-easy_handeye_calibration_server-12*.log
[ INFO] [1668063405.667658169]: Stereo is NOT SUPPORTE

```
**这个看起来是没有成功启动easy_handeye的服务，也没有进行标定的两个窗口。弹出的所有窗口是这个样子：**
![eye_error](https://user-images.githubusercontent.com/82266183/201021743-faceac1a-1584-4df0-923b-e152931d9f73.png)

**Comment by penglongxiang** [comment]
您好，这不是xArm这边的问题，在开发视觉应用时涉及到很多第三方代码和库，需要您自己处理和解决，我们没有相应的视觉开发背景和经验。您可以按照错误提示定位到是哪个第三方代码的问题

**Comment by vimior** [comment]
@AtariaLee 
```bash
 File "/home/lee/catkin_ws/src/easy_handeye/easy_handeye/src/easy_handeye/handeye_calibration_backend_opencv.py", line 4, in <module>
    import transforms3d as tfs
ImportError: No module named transforms3d
```
看这输出，是没有`transforms3d`这个库，可能是缺少某些依赖库

**Comment by AtariaLee** [comment]
@vimior  这个问题我注意到了，并且已经解决，但是仍然会有这个报错，并不是这个的原因
